name: foodkie
description: "A comprehensive restaurant management app."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

    # Firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3

    # State Management
  provider: ^6.0.5

    # UI Components
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  flutter_svg: ^2.0.5
  lottie: ^2.4.0

    # Utils
  intl: ^0.18.1
  uuid: ^3.0.7
  image_picker: ^0.8.9
  path_provider: ^2.0.15
  shared_preferences: ^2.1.2
  fluttertoast: ^8.2.2
  flutter_local_notifications: ^14.1.1

    # Animations
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/