// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFOODkXh-QZGIRYUKKl2N1VXXXXXXXXXXXXX',
    appId: '1:123456789012:web:a1b2c3d4e5f6a7b8c9d0e1',
    messagingSenderId: '123456789012',
    projectId: 'foodkie-app',
    authDomain: 'foodkie-app.firebaseapp.com',
    storageBucket: 'foodkie-app.appspot.com',
    measurementId: 'G-XXXXXXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_VnfmDunbLlrM5EQGYYYYYYYYYYYYYY',
    appId: '1:123456789012:android:a1b2c3d4e5f6a7b8c9d0e1',
    messagingSenderId: '123456789012',
    projectId: 'foodkie-app',
    storageBucket: 'foodkie-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBslLFqBs1kjdfsdWHtZZZZZZZZZZZZZZ',
    appId: '1:123456789012:ios:a1b2c3d4e5f6a7b8c9d0e1',
    messagingSenderId: '123456789012',
    projectId: 'foodkie-app',
    storageBucket: 'foodkie-app.appspot.com',
    iosClientId: '123456789012-abcdefghijklmnopqrstuvwxyz123456.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodkie',
  );
}